version: '3'
services:
  db:
    image: mysql:5.7

    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      TZ: 'Asia/Tokyo'

    ports:
      - '3306:3306'
    
    networks:
      - network1

    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  app:
    image: node:12.2

    ports:
      - '3000:3000'

    networks:
      - network1 
    
    depends_on:
      - db
    
    volumes:
      - ./src:/app

    working_dir: /app

    command: >
      /bin/sh -c '
      npm install &&
      npm run dev
      '

networks:
  network1:
